name: Final Project

on:
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: ~1.19
      - name: Run coverage
        run: make coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  units:
    runs-on: ubuntu-latest
    needs:
      - lint
      - coverage
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ~1.19

      - uses: actions/checkout@v3

      - name: Unit tests
        run: make test
